# For the subscriptions

# union EventState = WorkOrderStateEnum | SessionStateEnum | ScoutingFindStateEnum | SessionUserStateEnum

type APIEvent {
  type: APIEventTypeEnum!
  createdAt: Timestamp!
  sessionId: ID
  orderId: ID,
  ScoutingFindID: ID,
  # State change events are what this was made for.
  state: String 
}

enum APIEventTypeEnum {
  # Session Events
  CREATED
  UPDATED
  DELETED
  JOINED
  LEFT
  # Mining Job Events
  MJ_CREATED
  MJ_UPDATED
  MJ_DELETED
  # Scouting Find events
  RC_CREATED
  RC_UPDATED
  RC_DELETED
  # Crew Share events
  CS_CREATED
  CS_UPDATED
  CS_DELETED
}